import { Deal, DealCategory } from "@/types";

export const DEALS: Deal[] = [
  {
    id: "spotify",
    brand: "Spotify",
    logoEmoji: "🎵",
    category: "streaming",
    headline: "50% off Premium",
    fullPrice: 11.99,
    studentPrice: 5.99,
    savingsPercent: 50,
    description: "Full Spotify Premium at half price. Verified through SheerID — takes under 2 minutes.",
    claimDifficulty: "easy",
    claimSteps: ["Go to spotify.com/us/student", "Enter your .edu email", "Verify via SheerID", "Done — discount applied instantly"],
    verificationMethod: "SheerID",
    claimUrl: "https://www.spotify.com/us/student/",
    isLocked: false,
    tags: ["music", "audio", "entertainment"],
  },
  {
    id: "apple-music",
    brand: "Apple Music",
    logoEmoji: "🎶",
    category: "streaming",
    headline: "45% off — $5.99/mo",
    fullPrice: 10.99,
    studentPrice: 5.99,
    savingsPercent: 45,
    description: "Student plan includes full Apple Music library. Verified via UNiDAYS.",
    claimDifficulty: "easy",
    claimSteps: ["Open Settings on iPhone or Music app on Mac", "Tap your name → Subscriptions", "Select Apple Music → Student Plan", "Verify with UNiDAYS using .edu email"],
    verificationMethod: "UNiDAYS",
    claimUrl: "https://www.apple.com/shop/buy-iphone/apple-music",
    isLocked: false,
    tags: ["music", "audio", "apple"],
  },
  {
    id: "youtube-premium",
    brand: "YouTube Premium",
    logoEmoji: "▶️",
    category: "streaming",
    headline: "43% off — $7.99/mo",
    fullPrice: 13.99,
    studentPrice: 7.99,
    savingsPercent: 43,
    description: "Ad-free YouTube + YouTube Music. Student plan verified through SheerID.",
    claimDifficulty: "easy",
    claimSteps: ["Visit youtube.com/premium/student", "Sign in with your Google account", "Verify enrollment via SheerID", "Enjoy ad-free viewing and YouTube Music"],
    verificationMethod: "SheerID",
    claimUrl: "https://www.youtube.com/premium/student",
    isLocked: false,
    tags: ["video", "music", "google"],
  },
  {
    id: "adobe-cc",
    brand: "Adobe Creative Cloud",
    logoEmoji: "🎨",
    category: "software",
    headline: "64% off — $19.99/mo",
    fullPrice: 54.99,
    studentPrice: 19.99,
    savingsPercent: 64,
    description: "All 20+ Creative Cloud apps including Photoshop, Illustrator, Premiere, and After Effects. Biggest dollar savings on this list.",
    claimDifficulty: "medium",
    claimSteps: ["Go to adobe.com/creativecloud/buy/students.html", "Select your country and school", "Enter your .edu email for verification", "Choose annual or monthly plan", "Verification may take up to 72 hours"],
    verificationMethod: ".edu email + institutional verification",
    claimUrl: "https://www.adobe.com/creativecloud/buy/students.html",
    isLocked: false,
    tags: ["design", "video", "photo", "creative"],
  },
  {
    id: "microsoft-365",
    brand: "Microsoft 365",
    logoEmoji: "📊",
    category: "software",
    headline: "Free with .edu — $0/mo",
    fullPrice: 9.99,
    studentPrice: 0,
    savingsPercent: 100,
    description: "Word, Excel, PowerPoint, Teams, OneDrive (1TB), and more — completely free for students with a .edu address.",
    claimDifficulty: "easy",
    claimSteps: ["Go to microsoft.com/en-us/education/products/office", "Enter your .edu email", "Sign in or create a Microsoft account", "Download and install — it's instant"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.microsoft.com/en-us/education/products/office",
    isLocked: false,
    tags: ["productivity", "office", "microsoft"],
  },
  {
    id: "notion",
    brand: "Notion Plus",
    logoEmoji: "📝",
    category: "software",
    headline: "Free Plus plan — $0/mo",
    fullPrice: 16,
    studentPrice: 0,
    savingsPercent: 100,
    description: "The full Notion Plus plan (unlimited blocks, unlimited file uploads) is completely free for students and educators.",
    claimDifficulty: "easy",
    claimSteps: ["Go to notion.so/product/notion-for-education", "Click 'Get Notion free'", "Sign up or sign in with your .edu email", "Upgrade is applied automatically"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.notion.so/product/notion-for-education",
    isLocked: false,
    tags: ["productivity", "notes", "workspace"],
  },
  {
    id: "github-student",
    brand: "GitHub Student Pack",
    logoEmoji: "💻",
    category: "software",
    headline: "Free Developer Pack — $0/mo",
    fullPrice: 19,
    studentPrice: 0,
    savingsPercent: 100,
    description: "GitHub Pro plus $200k+ in developer tools: free domains, cloud credits, CI/CD tools, design software, and more from 100+ partners.",
    claimDifficulty: "easy",
    claimSteps: ["Go to education.github.com/pack", "Sign in to GitHub", "Apply with .edu email and proof of enrollment", "Approved within 1-3 business days"],
    verificationMethod: ".edu email + school ID upload",
    claimUrl: "https://education.github.com/pack",
    isLocked: false,
    tags: ["developer", "coding", "tools"],
  },
  {
    id: "canva-pro",
    brand: "Canva Pro",
    logoEmoji: "🖌️",
    category: "software",
    headline: "Free Pro — $0/mo",
    fullPrice: 15,
    studentPrice: 0,
    savingsPercent: 100,
    description: "Canva Pro with premium templates, brand kits, background remover, and 100GB storage — free for students.",
    claimDifficulty: "easy",
    claimSteps: ["Go to canva.com/education", "Click 'Get verified'", "Enter your .edu email or upload proof of enrollment", "Instant access to Pro features"],
    verificationMethod: ".edu email or enrollment proof",
    claimUrl: "https://www.canva.com/education/",
    isLocked: false,
    tags: ["design", "graphics", "templates"],
  },
  {
    id: "amazon-prime",
    brand: "Amazon Prime",
    logoEmoji: "📦",
    category: "streaming",
    headline: "50% off — $7.49/mo",
    fullPrice: 14.99,
    studentPrice: 7.49,
    savingsPercent: 50,
    description: "Prime Video, free 2-day shipping, Prime Music, and more at half price. Free 6-month trial included.",
    claimDifficulty: "easy",
    claimSteps: ["Go to amazon.com/joinstudent", "Sign in with your Amazon account", "Enter your .edu email to verify", "Enjoy a free 6-month trial, then 50% off"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.amazon.com/joinstudent",
    isLocked: false,
    tags: ["shopping", "video", "shipping"],
  },
  {
    id: "nytimes",
    brand: "New York Times",
    logoEmoji: "📰",
    category: "education",
    headline: "94% off — $1/mo",
    fullPrice: 17,
    studentPrice: 1,
    savingsPercent: 94,
    description: "Full digital access to the NYT — news, cooking, games, and the Wirecutter — for just $1/month for up to 4 years.",
    claimDifficulty: "easy",
    claimSteps: ["Go to nytimes.com/subscription/students", "Enter your .edu email", "Select the student plan", "Verify and subscribe — $1/month for 4 years"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.nytimes.com/subscription/students",
    isLocked: false,
    tags: ["news", "reading", "media"],
  },
  {
    id: "figma",
    brand: "Figma Professional",
    logoEmoji: "✏️",
    category: "software",
    headline: "Free Professional — $0/mo",
    fullPrice: 15,
    studentPrice: 0,
    savingsPercent: 100,
    description: "Figma's full Professional plan — unlimited projects, version history, and advanced prototyping — free for students.",
    claimDifficulty: "easy",
    claimSteps: ["Go to figma.com/education", "Sign in to your Figma account", "Apply with .edu email", "Verified within 1-3 business days"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.figma.com/education/",
    isLocked: true,
    tags: ["design", "ui", "prototyping"],
  },
  {
    id: "calm",
    brand: "Calm Premium",
    logoEmoji: "🧘",
    category: "health",
    headline: "87% off — $1.99/mo",
    fullPrice: 14.99,
    studentPrice: 1.99,
    savingsPercent: 87,
    description: "The full Calm app — sleep stories, guided meditations, and stress relief — nearly free for students via UNiDAYS.",
    claimDifficulty: "medium",
    claimSteps: ["Go to calm.com/student", "Connect your UNiDAYS account", "Verify your student status", "Subscribe at $1.99/month"],
    verificationMethod: "UNiDAYS",
    claimUrl: "https://www.calm.com/student",
    isLocked: true,
    tags: ["mental health", "sleep", "meditation"],
  },
  {
    id: "headspace",
    brand: "Headspace",
    logoEmoji: "🧠",
    category: "health",
    headline: "23% off — $9.99/mo",
    fullPrice: 12.99,
    studentPrice: 9.99,
    savingsPercent: 23,
    description: "Guided meditation, focus music, and sleep content. Student discount applied through SheerID.",
    claimDifficulty: "easy",
    claimSteps: ["Go to headspace.com/students", "Verify student status via SheerID", "Subscribe at the student rate"],
    verificationMethod: "SheerID",
    claimUrl: "https://www.headspace.com/students",
    isLocked: true,
    tags: ["mental health", "meditation", "focus"],
  },
  {
    id: "wsj",
    brand: "Wall Street Journal",
    logoEmoji: "📈",
    category: "education",
    headline: "90% off — $4/mo",
    fullPrice: 38.99,
    studentPrice: 4,
    savingsPercent: 90,
    description: "Full WSJ digital access — essential for business, finance, and economics grad students. Verified via .edu.",
    claimDifficulty: "easy",
    claimSteps: ["Go to wsj.com/studentoffer", "Enter your .edu email", "Create or sign into your WSJ account", "Subscribe at $4/month"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.wsj.com/studentoffer",
    isLocked: true,
    tags: ["news", "finance", "business"],
  },
  {
    id: "coursera-plus",
    brand: "Coursera Plus",
    logoEmoji: "🎓",
    category: "education",
    headline: "Free access via your university",
    fullPrice: 59,
    studentPrice: 0,
    savingsPercent: 100,
    description: "Many universities grant free Coursera Plus access to enrolled students. Thousands of courses, certificates, and specializations.",
    claimDifficulty: "medium",
    claimSteps: ["Check if your university has a Coursera partnership at coursera.org/campus", "Log in with your .edu email", "If your school is partnered, access is instant", "Otherwise, apply for financial aid (takes 15 days)"],
    verificationMethod: "Institutional partnership or .edu email",
    claimUrl: "https://www.coursera.org/for-campus/students",
    isLocked: true,
    tags: ["courses", "certificates", "learning"],
  },
  {
    id: "grammarly",
    brand: "Grammarly Premium",
    logoEmoji: "✍️",
    category: "software",
    headline: "Free Premium via institution",
    fullPrice: 30,
    studentPrice: 0,
    savingsPercent: 100,
    description: "Many universities license Grammarly Premium for all students. Check if yours does before paying — most people don't.",
    claimDifficulty: "easy",
    claimSteps: ["Go to grammarly.com/edu", "Enter your .edu email", "If your institution has a license, you'll get instant Premium access", "Otherwise, use UNiDAYS for a discount"],
    verificationMethod: "Institutional license or UNiDAYS",
    claimUrl: "https://www.grammarly.com/edu",
    isLocked: true,
    tags: ["writing", "productivity", "grammar"],
  },
  {
    id: "expressvpn",
    brand: "ExpressVPN",
    logoEmoji: "🔒",
    category: "software",
    headline: "Free via GitHub Student Pack",
    fullPrice: 12.95,
    studentPrice: 0,
    savingsPercent: 100,
    description: "3 months of ExpressVPN free when you redeem through the GitHub Student Developer Pack. No credit card needed.",
    claimDifficulty: "easy",
    claimSteps: ["Get the GitHub Student Developer Pack (education.github.com/pack)", "Find ExpressVPN in the pack", "Redeem your 3-month code", "Extend with GitHub Pack renewal each year"],
    verificationMethod: "GitHub Student Pack",
    claimUrl: "https://education.github.com/pack",
    isLocked: true,
    tags: ["vpn", "security", "privacy"],
  },
  {
    id: "chegg",
    brand: "Chegg Study",
    logoEmoji: "📚",
    category: "education",
    headline: "38% off — $9.95/mo",
    fullPrice: 15.95,
    studentPrice: 9.95,
    savingsPercent: 38,
    description: "Textbook solutions, expert Q&A, and study guides. Discount applied via .edu verification.",
    claimDifficulty: "easy",
    claimSteps: ["Go to chegg.com/study", "Sign up or sign in", "Verify with .edu email for student pricing", "Subscribe at the reduced rate"],
    verificationMethod: ".edu email",
    claimUrl: "https://www.chegg.com/study",
    isLocked: true,
    tags: ["textbooks", "homework", "tutoring"],
  },
  {
    id: "peloton",
    brand: "Peloton App",
    logoEmoji: "🚴",
    category: "health",
    headline: "46% off — $6.99/mo",
    fullPrice: 12.99,
    studentPrice: 6.99,
    savingsPercent: 46,
    description: "Full Peloton app — cycling, running, strength, yoga, meditation — no equipment required.",
    claimDifficulty: "medium",
    claimSteps: ["Go to onepeloton.com/app/student", "Verify via UNiDAYS", "Subscribe at the student rate"],
    verificationMethod: "UNiDAYS",
    claimUrl: "https://www.onepeloton.com/app/student",
    isLocked: true,
    tags: ["fitness", "workout", "exercise"],
  },
  {
    id: "autodesk",
    brand: "Autodesk Suite",
    logoEmoji: "📐",
    category: "software",
    headline: "Free 1-year license — $0",
    fullPrice: 270,
    studentPrice: 0,
    savingsPercent: 100,
    description: "AutoCAD, Revit, Fusion 360, Maya, 3ds Max — the full Autodesk suite free for students and educators for 1 year (renewable).",
    claimDifficulty: "medium",
    claimSteps: ["Go to autodesk.com/education/edu-software", "Create an Autodesk account with .edu email", "Verify enrollment (may require school name + enrollment confirmation)", "Download directly — 1-year license, renewable"],
    verificationMethod: ".edu email + enrollment verification",
    claimUrl: "https://www.autodesk.com/education/edu-software",
    isLocked: true,
    tags: ["cad", "3d", "engineering", "architecture"],
  },
];

export function getDealsByCategory(category: DealCategory): Deal[] {
  return DEALS.filter((d) => d.category === category);
}

export function getFeaturedDeals(count: number): Deal[] {
  return DEALS.filter((d) => !d.isLocked).slice(0, count);
}

export function getAllCategories(): DealCategory[] {
  return [...new Set(DEALS.map((d) => d.category))];
}
