import { Deal, DealCategory } from "@/types";

export const DEALS: Deal[] = [
  {
    id: "spotify", brand: "Spotify", logoEmoji: "🎵", logoDomain: "spotify.com", category: "streaming",
    headline: "50% off Premium", fullPrice: 11.99, studentPrice: 5.99, savingsPercent: 50,
    description: "Full Spotify Premium at half price. Verified through SheerID — takes under 2 minutes.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands directly on the SheerID verification form", "Enter your school name and .edu email", "SheerID verifies instantly — discount applied to your account"],
    verificationMethod: "SheerID", claimUrl: "https://www.spotify.com/us/student/", tags: ["music", "audio", "entertainment"],
  },
  {
    id: "apple-music", brand: "Apple Music", logoEmoji: "🎶", logoDomain: "apple.com", category: "streaming",
    headline: "45% off — $5.99/mo", fullPrice: 10.99, studentPrice: 5.99, savingsPercent: 45,
    description: "Student plan includes full Apple Music library. Verified via UNiDAYS.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to the Apple Music student plan page", "Click 'Get student offer'", "Verify your enrollment through UNiDAYS with your .edu email", "Subscribe at $5.99/month"],
    verificationMethod: "UNiDAYS", claimUrl: "https://music.apple.com/us/student", tags: ["music", "audio", "apple"],
  },
  {
    id: "youtube-premium", brand: "YouTube Premium", logoEmoji: "▶️", logoDomain: "youtube.com", category: "streaming",
    headline: "43% off — $7.99/mo", fullPrice: 13.99, studentPrice: 7.99, savingsPercent: 43,
    description: "Ad-free YouTube + YouTube Music. Student plan verified through SheerID.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands on the YouTube Premium student plan page", "Sign in with your Google account", "Click 'Try it free' — triggers SheerID verification", "Enter your school and .edu email to verify"],
    verificationMethod: "SheerID", claimUrl: "https://www.youtube.com/premium/student", tags: ["video", "music", "google"],
  },
  {
    id: "hulu", brand: "Hulu", logoEmoji: "📺", logoDomain: "hulu.com", category: "streaming",
    headline: "89% off — $1.99/mo", fullPrice: 17.99, studentPrice: 1.99, savingsPercent: 89,
    description: "Full Hulu streaming library (with ads) for $1.99/month. One of the best streaming deals available to students.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands directly on Hulu's student plan page", "Sign in or create a Hulu account", "Enter your .edu email — SheerID verifies enrollment instantly", "Subscribe at $1.99/month"],
    verificationMethod: "SheerID", claimUrl: "https://www.hulu.com/student", tags: ["tv", "video", "movies"],
  },
  {
    id: "tidal", brand: "Tidal", logoEmoji: "🌊", logoDomain: "tidal.com", category: "streaming",
    headline: "45% off — $5.99/mo", fullPrice: 10.99, studentPrice: 5.99, savingsPercent: 45,
    description: "High-fidelity lossless audio and HiRes FLAC streaming at student pricing. Verified through SheerID.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to Tidal's student plan page", "Sign in or create a Tidal account", "Enter your school name and .edu email — SheerID verifies instantly", "Subscribe at $5.99/month"],
    verificationMethod: "SheerID", claimUrl: "https://tidal.com/us/student", tags: ["music", "hifi", "audio"],
  },
  {
    id: "amazon-prime", brand: "Amazon Prime", logoEmoji: "📦", logoDomain: "amazon.com", category: "streaming",
    headline: "50% off — $7.49/mo", fullPrice: 14.99, studentPrice: 7.49, savingsPercent: 50,
    description: "Prime Video, free 2-day shipping, Prime Music, and more at half price. 6-month free trial included.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands on the Amazon Prime Student enrollment page", "Sign in with your Amazon account", "Enter your .edu email to verify student status", "Start your free 6-month trial — then 50% off Prime going forward"],
    verificationMethod: ".edu email", claimUrl: "https://www.amazon.com/joinstudent", tags: ["shopping", "video", "shipping"],
  },
  {
    id: "adobe-cc", brand: "Adobe Creative Cloud", logoEmoji: "🎨", logoDomain: "adobe.com", category: "software",
    headline: "64% off — $19.99/mo", fullPrice: 54.99, studentPrice: 19.99, savingsPercent: 64,
    description: "All 20+ Creative Cloud apps including Photoshop, Illustrator, Premiere, and After Effects. Biggest dollar savings on this list.",
    claimDifficulty: "medium",
    claimSteps: ["Click the button below — lands directly on Adobe's student purchase page", "Select your country and enter your school name", "Enter your .edu email — Adobe verifies via SheerID or institutional check", "Choose annual plan (billed monthly or upfront) and complete checkout", "Verification is usually instant; may take up to 72 hours if manual review needed"],
    verificationMethod: "SheerID", claimUrl: "https://www.adobe.com/creativecloud/buy/students.html", tags: ["design", "video", "photo", "creative"],
  },
  {
    id: "microsoft-365", brand: "Microsoft 365", logoEmoji: "📊", logoDomain: "microsoft.com", category: "software",
    headline: "Free for 12 months — $0", fullPrice: 9.99, studentPrice: 0, savingsPercent: 100,
    description: "Word, Excel, PowerPoint, Teams, OneDrive (1TB), and more — free for 12 months for verified college students.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to the student pricing page", "Click 'Sign up' and enter your .edu email", "Sign in or create a free Microsoft account", "Microsoft verifies your student status instantly via your .edu email", "Download and install — all apps available immediately"],
    verificationMethod: ".edu email", claimUrl: "https://www.microsoft.com/en-us/microsoft-365/college-student-pricing", tags: ["productivity", "office", "microsoft"],
  },
  {
    id: "notion", brand: "Notion Plus", logoEmoji: "📝", logoDomain: "notion.so", category: "software",
    headline: "Free Plus plan — $0/mo", fullPrice: 16, studentPrice: 0, savingsPercent: 100,
    description: "The full Notion Plus plan — unlimited blocks, unlimited file uploads — free for students. Verified with your .edu email.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to Notion's education page", "Click 'Get Notion free' and sign up with your .edu email", "Once signed in, go to Settings → Plans", "Click 'Get free Education plan' — upgrade is applied instantly"],
    verificationMethod: ".edu email", claimUrl: "https://www.notion.com/product/notion-for-education", tags: ["productivity", "notes", "workspace"],
  },
  {
    id: "github-student", brand: "GitHub Student Pack", logoEmoji: "💻", logoDomain: "github.com", category: "software",
    headline: "Free Developer Pack — $0/mo", fullPrice: 19, studentPrice: 0, savingsPercent: 100,
    description: "GitHub Pro plus $200k+ in developer tools: free domains, cloud credits, CI/CD tools, design software, and more from 100+ partners.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to the application form", "Sign in to your GitHub account", "Enter your .edu email and select your school from the dropdown", "Upload a proof of enrollment if your .edu isn't auto-verified", "Approved within 1–3 business days"],
    verificationMethod: ".edu email + enrollment proof", claimUrl: "https://education.github.com/pack/join", tags: ["developer", "coding", "tools"],
  },
  {
    id: "canva-pro", brand: "Canva Pro", logoEmoji: "🖌️", logoDomain: "canva.com", category: "software",
    headline: "Free Pro — $0/mo", fullPrice: 15, studentPrice: 0, savingsPercent: 100,
    description: "Canva Pro with premium templates, brand kits, background remover, and 100GB storage — free for higher-ed students.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to the Canva student education page", "Click 'Get verified' and sign in or create a Canva account", "Enter your .edu email — verification is usually instant", "Pro features unlock immediately on your account"],
    verificationMethod: ".edu email", claimUrl: "https://www.canva.com/education/students/", tags: ["design", "graphics", "templates"],
  },
  {
    id: "figma", brand: "Figma Professional", logoEmoji: "✏️", logoDomain: "figma.com", category: "software",
    headline: "Free Professional — $0/mo", fullPrice: 15, studentPrice: 0, savingsPercent: 100,
    description: "Figma's full Professional plan — unlimited projects, version history, and advanced prototyping — free for students.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to the Figma Education application form", "Sign in to your Figma account", "Select 'Student' and enter your school and .edu email", "SheerID verifies your enrollment — approved within 1–3 business days"],
    verificationMethod: "SheerID", claimUrl: "https://www.figma.com/education/apply", tags: ["design", "ui", "prototyping"],
  },
  {
    id: "jetbrains", brand: "JetBrains All Products", logoEmoji: "⚡", logoDomain: "jetbrains.com", category: "software",
    headline: "Free all-products license — $0", fullPrice: 24.90, studentPrice: 0, savingsPercent: 100,
    description: "Every JetBrains IDE free — IntelliJ IDEA, PyCharm, WebStorm, DataGrip, CLion, GoLand, and more. Renewable annually while enrolled.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to JetBrains' student application form", "Sign in or create a JetBrains account", "Enter your .edu email — JetBrains verifies within 1–3 business days", "Download and activate any JetBrains IDE with your student license", "Renewable each year for free as long as you're a student"],
    verificationMethod: ".edu email", claimUrl: "https://www.jetbrains.com/student/", tags: ["developer", "ide", "coding", "python", "javascript"],
  },
  {
    id: "nordvpn", brand: "NordVPN", logoEmoji: "🛡️", logoDomain: "nordvpn.com", category: "software",
    headline: "71% off — $3.49/mo", fullPrice: 11.99, studentPrice: 3.49, savingsPercent: 71,
    description: "Top-rated VPN for privacy, security, and accessing geo-restricted content — student deal through UNiDAYS.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to the NordVPN UNiDAYS discount page", "Verify your student status with UNiDAYS (free, uses your .edu email)", "Click through to NordVPN with the discount applied", "Choose your plan length — longer plans give the best per-month rate"],
    verificationMethod: "UNiDAYS", claimUrl: "https://www.myunidays.com/US/en-US/partners/nordvpn/view", tags: ["vpn", "security", "privacy"],
  },
  {
    id: "1password", brand: "1Password", logoEmoji: "🔑", logoDomain: "1password.com", category: "software",
    headline: "Free via Student Pack — $0", fullPrice: 2.99, studentPrice: 0, savingsPercent: 100,
    description: "The best password manager, free through the GitHub Student Developer Pack. Works on all devices — Mac, Windows, iOS, Android.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to 1Password's student offer page", "Sign up with your .edu email to verify student status", "Create a 1Password account — your free subscription is applied automatically", "Download the app on all your devices"],
    verificationMethod: ".edu email", claimUrl: "https://1password.com/students/", tags: ["password", "security", "productivity"],
  },
  {
    id: "unity-student", brand: "Unity Student Plan", logoEmoji: "🎮", logoDomain: "unity.com", category: "software",
    headline: "Free Student Plan — $0", fullPrice: 185, studentPrice: 0, savingsPercent: 100,
    description: "Unity's game engine with Student Plan features — free for enrolled students. Build games, simulations, AR/VR, and interactive experiences.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to Unity's student plan page", "Sign in or create a Unity ID", "Click 'Get started' and enter your .edu email", "Unity verifies via your email domain — access granted immediately", "Download Unity Hub and install the Unity Editor"],
    verificationMethod: ".edu email", claimUrl: "https://unity.com/products/unity-student", tags: ["game-dev", "3d", "ar", "vr"],
  },
  {
    id: "grammarly", brand: "Grammarly Premium", logoEmoji: "✍️", logoDomain: "grammarly.com", category: "software",
    headline: "25% off via UNiDAYS", fullPrice: 30, studentPrice: 22.50, savingsPercent: 25,
    description: "25% off Grammarly Premium via UNiDAYS. Also worth checking if your university has a free institutional license — many do.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to the Grammarly UNiDAYS discount page", "Verify your student status with UNiDAYS", "Receive your discount code and click through to Grammarly checkout", "Pro tip: also check grammarly.com/edu with your .edu email — your university may have a free license"],
    verificationMethod: "UNiDAYS", claimUrl: "https://www.myunidays.com/US/en-US/partners/grammarly/view", tags: ["writing", "productivity", "grammar"],
  },
  {
    id: "expressvpn", brand: "ExpressVPN", logoEmoji: "🔒", logoDomain: "expressvpn.com", category: "software",
    headline: "69% off + 3 months free", fullPrice: 12.95, studentPrice: 3.99, savingsPercent: 69,
    description: "Up to 69% off a 1-year subscription plus 3 extra months free — verified directly through UNiDAYS.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to the ExpressVPN UNiDAYS discount page", "Verify your student status with UNiDAYS", "Click through to ExpressVPN with the discount automatically applied", "Complete checkout — discount applied at checkout"],
    verificationMethod: "UNiDAYS", claimUrl: "https://www.myunidays.com/US/en-US/partners/expressvpn/view", tags: ["vpn", "security", "privacy"],
  },
  {
    id: "autodesk", brand: "Autodesk Suite", logoEmoji: "📐", logoDomain: "autodesk.com", category: "software",
    headline: "Free 1-year license — $0", fullPrice: 270, studentPrice: 0, savingsPercent: 100,
    description: "AutoCAD, Revit, Fusion 360, Maya, 3ds Max — the full Autodesk suite free for students for 1 year, renewable annually.",
    claimDifficulty: "medium",
    claimSteps: ["Click the button below — goes directly to Autodesk's education software catalog", "Select the product you want (AutoCAD, Revit, Fusion 360, etc.)", "Click 'Get product' and create an Autodesk account with your .edu email", "SheerID verifies your enrollment — 1-year free license granted immediately", "Renewable each year for as long as you're a student"],
    verificationMethod: "SheerID", claimUrl: "https://www.autodesk.com/education/edu-software/overview", tags: ["cad", "3d", "engineering", "architecture"],
  },
  {
    id: "nytimes", brand: "New York Times", logoEmoji: "📰", logoDomain: "nytimes.com", category: "education",
    headline: "94% off — $1/mo", fullPrice: 17, studentPrice: 1, savingsPercent: 94,
    description: "Full NYT digital access — news, cooking, games, and Wirecutter — for $1/month for up to 4 years.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands directly on the NYT student subscription page", "Enter your .edu email address", "Select the student plan and complete checkout", "$1/month billed — valid for up to 4 years while enrolled"],
    verificationMethod: ".edu email", claimUrl: "https://www.nytimes.com/subscription/students", tags: ["news", "reading", "media"],
  },
  {
    id: "wsj", brand: "Wall Street Journal", logoEmoji: "📈", logoDomain: "wsj.com", category: "education",
    headline: "90% off — $4/mo", fullPrice: 38.99, studentPrice: 4, savingsPercent: 90,
    description: "Full WSJ digital access — essential for business, finance, and economics students. Verified via SheerID.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands directly on WSJ's student subscription page", "Enter your .edu email — SheerID verifies your enrollment", "Complete checkout at $4/month"],
    verificationMethod: "SheerID", claimUrl: "https://www.wsj.com/student", tags: ["news", "finance", "business"],
  },
  {
    id: "coursera-plus", brand: "Coursera Plus", logoEmoji: "🎓", logoDomain: "coursera.org", category: "education",
    headline: "40% off first 3 months", fullPrice: 59, studentPrice: 35.40, savingsPercent: 40,
    description: "40% off Coursera Plus for your first 3 months — thousands of courses, professional certificates, and specializations.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes to the Coursera UNiDAYS discount page", "Verify your student status with UNiDAYS (free account, uses .edu email)", "Receive a discount code and click through to Coursera", "Apply the code at checkout — 40% off your first 3 months"],
    verificationMethod: "UNiDAYS", claimUrl: "https://www.myunidays.com/US/en-US/partners/coursera/view", tags: ["courses", "certificates", "learning"],
  },
  {
    id: "datacamp", brand: "DataCamp", logoEmoji: "📊", logoDomain: "datacamp.com", category: "education",
    headline: "Free via Student Pack — $0/mo", fullPrice: 25, studentPrice: 0, savingsPercent: 100,
    description: "Learn Python, R, SQL, data science, and machine learning — free through the GitHub Student Developer Pack. 400+ courses.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to the DataCamp student offer page", "Verify your enrollment via the GitHub Student Developer Pack (free, takes 2 min)", "Create a DataCamp account — 3 months free Premium access applied", "Access all courses, projects, and career tracks"],
    verificationMethod: "GitHub Student Pack", claimUrl: "https://www.datacamp.com/github-students", tags: ["data-science", "python", "machine-learning", "sql"],
  },
  {
    id: "economist", brand: "The Economist", logoEmoji: "🌍", logoDomain: "economist.com", category: "education",
    headline: "68% off — $7/mo", fullPrice: 22, studentPrice: 7, savingsPercent: 68,
    description: "Full digital access to The Economist — global politics, economics, business, and culture. Steep student discount for up to 2 years.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to The Economist's student subscription page", "Enter your .edu email to verify enrollment", "Select the student plan and complete checkout", "Available while enrolled, typically up to 2 years"],
    verificationMethod: ".edu email", claimUrl: "https://www.economist.com/student", tags: ["news", "economics", "business", "global"],
  },
  {
    id: "calm", brand: "Calm Premium", logoEmoji: "🧘", logoDomain: "calm.com", category: "health",
    headline: "77% off — $3.50/mo", fullPrice: 14.99, studentPrice: 3.50, savingsPercent: 77,
    description: "The full Calm app — sleep stories, guided meditations, and stress relief — at a steep student rate. US students 18+ only.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — goes directly to Calm's student plan page", "Sign in or create a Calm account", "Enter your .edu email to verify your student status", "Subscribe at the student rate — discount applied immediately"],
    verificationMethod: ".edu email", claimUrl: "https://www.calm.com/students", tags: ["mental health", "sleep", "meditation"],
  },
  {
    id: "headspace", brand: "Headspace", logoEmoji: "🧠", logoDomain: "headspace.com", category: "health",
    headline: "94% off — $9.99/year", fullPrice: 12.99, studentPrice: 0.83, savingsPercent: 94,
    description: "Guided meditation, focus music, and sleep content — $9.99 for a full year (not month). Verified directly through SheerID.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands directly on the SheerID-powered student checkout page", "Enter your university name and .edu email", "SheerID verifies instantly — you're taken straight to checkout at $9.99/year"],
    verificationMethod: "SheerID", claimUrl: "https://www.headspace.com/studentplan", tags: ["mental health", "meditation", "focus"],
  },
  {
    id: "peloton", brand: "Peloton App", logoEmoji: "🚴", logoDomain: "onepeloton.com", category: "health",
    headline: "46% off — $6.99/mo", fullPrice: 12.99, studentPrice: 6.99, savingsPercent: 46,
    description: "Full Peloton app — cycling, running, strength, yoga, meditation — no equipment required. Verified via ID.me.",
    claimDifficulty: "medium",
    claimSteps: ["Click the button below — lands on Peloton's student discount page", "Click 'Verify with ID.me' — create a free ID.me account if you don't have one", "Verify your student status through ID.me using your .edu email or enrollment documents", "Subscribe at $6.99/month"],
    verificationMethod: "ID.me", claimUrl: "https://www.onepeloton.com/student", tags: ["fitness", "workout", "exercise"],
  },
  {
    id: "doordash-dashpass", brand: "DoorDash DashPass", logoEmoji: "🍕", logoDomain: "doordash.com", category: "food",
    headline: "50% off — $4.99/mo", fullPrice: 9.99, studentPrice: 4.99, savingsPercent: 50,
    description: "DashPass for students — free delivery, reduced service fees, and exclusive restaurant offers. Saves on every order.",
    claimDifficulty: "easy",
    claimSteps: ["Click the button below — lands directly on DoorDash's student DashPass page", "Sign in or create a DoorDash account", "Enter your .edu email — SheerID verifies your enrollment instantly", "Subscribe at $4.99/month (vs $9.99 standard)"],
    verificationMethod: "SheerID", claimUrl: "https://www.doordash.com/dashpass/student", tags: ["food-delivery", "restaurants", "delivery"],
  },
];

export function getDealsByCategory(category: DealCategory): Deal[] {
  return DEALS.filter((d) => d.category === category);
}

export function getFeaturedDeals(count: number): Deal[] {
  return DEALS.slice(0, count);
}

export function getAllCategories(): DealCategory[] {
  return [...new Set(DEALS.map((d) => d.category))];
}
